<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3791c8ff-0045-4766-bf64-8fa66d9ac5b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Play video&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='udemy']/div[2]/div/div/div/main/div/div/div/div/div/div/div/div/div/div/div/section/div/div/div/div/div/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>96</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>96</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Play video</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/staticx/udemy/js/webpack/icon-play.ac3f32ecb72a0c3f674fa5a3f3062a56.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;udemy&quot;)/div[@class=&quot;main-content-wrapper&quot;]/div[@class=&quot;main-content&quot;]/div[@class=&quot;ud-app-loader ud-component--course-taking--app w100p h100p ud-app-loaded&quot;]/div[@class=&quot;app--no-sidebar--1naXE&quot;]/main[@class=&quot;app--column-container--3AItG&quot;]/div[@class=&quot;app--content-column--HC_i1&quot;]/div[@class=&quot;app--row--1ydzX app--body-container--10gJo&quot;]/div[@class=&quot;app--row-content--1lH7B&quot;]/div[@class=&quot;app--curriculum-item--2GBGE&quot;]/div[@class=&quot;curriculum-item-view--scaled-height-limiter--1j3Pp curriculum-item-view--no-sidebar--L4DBG&quot;]/div[@class=&quot;curriculum-item-view--absolute-height-limiter--1SMqE curriculum-item-view--no-sidebar--L4DBG&quot;]/div[@class=&quot;curriculum-item-view--aspect-ratio-container--2tJ-p&quot;]/div[@class=&quot;curriculum-item-view--content-container--2MIL1&quot;]/div[@class=&quot;curriculum-item-view--scaled-height-limiter--1j3Pp curriculum-item-view--no-sidebar--L4DBG&quot;]/div[@class=&quot;curriculum-item-view--absolute-height-limiter--1SMqE curriculum-item-view--no-sidebar--L4DBG&quot;]/div[@class=&quot;curriculum-item-view--content--3ABmp curriculum-item-view--video-background--lcepY&quot;]/section[@class=&quot;lecture-view--container--pL22J&quot;]/div[@class=&quot;video-viewer--container--23VX7&quot;]/div[@class=&quot;video-player--container--YDQRW&quot;]/div[@class=&quot;video-player--video-wrapper--1L212&quot;]/div[1]/div[@class=&quot;video-player--center-button--aPLkI&quot;]/button[1]/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='udemy']/div[2]/div/div/div/main/div/div/div/div/div/div/div/div/div/div/div/section/div/div/div/div/div/button/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Play video']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
   </webElementXpaths>
</WebElementEntity>
